DROP INDEX IF EXISTS idx_vendors_search;
ALTER TABLE vendors DROP COLUMN IF EXISTS search_tsv;

DROP TABLE IF EXISTS fcm_tokens;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS users;
